name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: make NAME
      run: make

    - name: clean
      run: make fclean

    - name: fclean
      run: make fclean

  test:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: test
      run: make test
